### ISSUE TITLE
Yeelight sunflower unavailable

### ISSUE THREAD

**Issue by cyberluke** [lindsaymarkward/python-yeelight-sunflower#1]
Hi, some other coder here to help.

I have enabled debug log for yeelight. It just shows normal data, no exceptions.

But in UI it becomes unavailable a looot of times. Yeelink next to bulb, mobile app tells signal is strong.

From console I recognize the whole system (home assistant) keeps asking LG webOS for app list.

Can it be something with not remembering the state of Yeelight in your code?

Now this came to a log file and status is still unavailable for both bulbs (third, the middle one is disconnected):

`[36m2018-03-27 22:57:57 DEBUG (SyncWorker_1) [yeelightsunflower.main] !Got response: S 035F,1,1,81,[0m0,255,43,0`

`[36m2018-03-27 22:57:57 DEBUG (SyncWorker_1) [yeelightsunflower.main] Received: GLB 0001,1,0,123,25[0m191,100,0;0002,1,0,0,255,255,255,100,0;035F,1,0,81,255,0,255,43,0;`

`[36m2018-03-27 22:57:57 DEBUG (SyncWorker_1) [yeelightsunflower.main] get_data response: 'GLB 0001,1,0,123,255,0,191,100,0;0002,1,0,0,255,255,255,100,0;035F,1,0,81,255,0,255,43,0;\r'[0m`

`[36m2018-03-27 22:57:57 DEBUG (SyncWorker_1) [yeelightsunflower.main] got: {'0001': [0, 255, 0, 191, 100], '0002': [0, 255, 255, 255, 100], '035F': [0, 255, 0, 255, 43]}[0m`

**Comment by cyberluke** [comment]
Now after 3 minutes, doing nothing, when writing this post and both became available in UI again. Several seconds later: unavailable :-)

**Comment by cyberluke** [comment]
Ok, so for me the solution is that even when yeelink returns status 0 for bulb, it just means it is turned off. It does not mean it is unavailable. I can turn it on by sending ANY command ANYTIME.

Setting it to 1 forever here fixes it for me [main.py]:
```        # deconstruct response string into light data. Example data:
        # GLB 143E,1,1,25,255,255,255,0,0;287B,1,1,22,255,255,255,0,0;\r\n
        response = response[4:-3]  # strip start (GLB) and end (;\r\n)
        light_strings = response.split(';')
        light_data_by_id = {}
        for light_string in light_strings:
            values = light_string.split(',')
            try:
                _LOGGER.debug("%s now online: %s %s", values[0], int(values[2]), values[2])
                values[2] = 1
                light_data_by_id[values[0]] = [int(values[2]), int(values[4]),
                                               int(values[5]), int(values[6]),
                                               int(values[7])]
```

Then there's some bug that two sliders in UI get enabled/disabled at the same time by clicking on first or second (on/off switch).

**Comment by cyberluke** [comment]
Also had to change this in Python36-32\Lib\site-packages\homeassistant\components\light\yeelightsunflower.py:

```    def update(self):
        """Fetch new state data for this light and update local values."""
        self._light.update()
        #self._available = self._light.available
        self._available = 1
```

**Comment by cyberluke** [comment]
hey what's up?

**Comment by lindsaymarkward** [comment]
Hi. Sorry, I didn't see your issue from 3 weeks ago. I'll have to change my GitHub notification settings.
Thanks for your input.

I don't have the same problem as you with my Yeelight Sunflower bulbs.
Setting `_available` to 1 (True) might be a workaround, but it breaks expected functionality.
When the bulb is unavailable (e.g. unplugged), it _should_ show as unavailable.

What do you mean by "Yeelink next to bulb, mobile app tells signal is strong." - Which app are you using?
What do you mean by "Then there's some bug that two sliders in UI get enabled/disabled at the same time by clicking on first or second (on/off switch)."?
Do you think you could edit your log output to fix the non-printing characters... or is this actually what you see? (E.g. `81,�[0m0`)
Are you using the latest version (0.0.10)?

Thanks!

**Comment by cyberluke** [comment]
1) I use official Yeelight Sunflower Android app

2) For me when the bulb is unavailable it is just not being present in the list. If it is in the response list and available=0, I just send turnOn command and it works as it should

3) the slider UI random switch is caused by homeassistant caching or querying the state from your component, there is some random noise proably due to "available" property

4) I think it is just some console bad character due to Windows / UTF-8 settings

**Comment by cyberluke** [comment]
Maybe I'm just compensating buggy chinese firmware, but my solution works.

**Comment by cyberluke** [comment]
My next step will be to cache Yeelight addresses from previous HomeAssistant startup or put it in static list in configuration.

**Comment by lindsaymarkward** [comment]
I wonder if we have different hardware/firmware versions...
I just installed the Android app and it reports my firmware is 2.1.1 - what does yours say?
It seems the issue is that the main issue is that your hub reports bulbs as unavailable when they're not. Does it always report '0' when they have zero brightness? Do you think maybe yours might be using a different data format - or is it just glitchy?

Can you explain 3. some more? I don't understand what you mean about the "slider UI random switch"...
I'll do what I can to look into it for you, but setting unavailable lights to available is not ideal.

**Comment by cyberluke** [comment]
I will be at home in 2 hours. Don't remember firmware version, but they don't have any firmware updates. That was the first thing I wanted to do: update firmware (link: https://www.yeelight.com/en_US/info/download)

Yes, when I set brightness to 0, it sets itself to unavailable after one or two getList requests.

The rest of the data including data format is correct. I checked firmware manual and numbers are correct. Color codes are also correct.

I have also Yeelight Blue and I'm Seeed Studio distributor (got Sunflower from here like 2 years ago).

Explain no. 3:
I might record video of this behavior. When I click on slider to switch off the light. The switch will go to off position. But after 5 seconds or so it will go back to on position. Then I click on it again and it will go to off position and stay there. It is just this quirk in UI, it does not turn on the light. The light keeps to be turned off all the time since the first action.

I found this also happens in other components such as LG WebOS or Spotify, when there was some bad configuration. You set something from UI, but HomeAssistant then uses some form of polling for states and when TV is not quick enough to change signal source for example, it will jump from one value to another in cycle.

I tried to describe it also here in HomeAssistant issues: https://github.com/home-assistant/home-assistant/issues/13513

**Comment by lindsaymarkward** [comment]
I bought the lights direct from the developers in mid 2014. I think it was effectively a 'beta' product that didn't have much future (no updates)... It's nice to find someone else who can use the code I've written for the lights... but a shame it doesn't work so well for you.
I have had the same problems with the light switches and other UI switches... mostly when I haven't reloaded the page for a while, so the state is out of synch. 

If your lights/hub are just reporting the wrong information then I think the simplest solution for you is to create a *custom component* https://www.home-assistant.io/developers/creating_components/ and copy my `yeelightsunflower.py` file then modify the availability part you've identified. You don't need to modify this library, which will continue to report the lights are unavailable, but the HA platform will ignore this and report it is OK.
Of course, you won't ever see when your lights are actually off...

**Comment by cyberluke** [comment]
Firmware: 2.1.2
Sofware version: 2.0.3

Ok, that sounds like a good solution. Thank you very much!

**Comment by lindsaymarkward** [comment]
Well, maybe they changed (broke!) something in that firmware version. 
Let me know if I can help with anything else 👍
